name: Deploy Shiny App to Posit Connect

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your app's Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rsconnect-python

      # Step 4: Authenticate with Posit Connect
      - name: Add Posit Connect Account
        run: |
          rsconnect add \
            --account xabilitylab \
            --name xabilitylab \
            --token ${{ secrets.POSIT_API_KEY }} \
            --secret ${{ secrets.POSIT_API_SECRET }}

      # Step 5: Deploy to Posit Connect
      - name: Deploy Application
        run: |
          rsconnect deploy shiny Dashboard \
            --name xabilitylab \
            --title pcha-dashboard
